<?xml version="1.0"?>
<Config>
  <Module>
    <Name>Brown Smart</Name>
    <PixelCols>32</PixelCols>
    <PixelRows>32</PixelRows>
    <DataDirectType>Horizontal</DataDirectType>
    <DriverChipType>Chip_MBI5124New</DriverChipType>
    <DriverChipTypeExtend>0</DriverChipTypeExtend>
    <DriverTypePro>0</DriverTypePro>
    <DecType>Decode138</DecType>
    <OEPolarity>LowEnable</OEPolarity>
    <ScanType>Scan_8</ScanType>
    <TotalPointInTable>64</TotalPointInTable>
    <DataGroup>2</DataGroup>
    <PointTableData>0-8-1-8-2-8-3-8-4-8-5-8-6-8-7-8-8-8-9-8-10-8-11-8-12-8-13-8-14-8-15-8-16-8-17-8-18-8-19-8-20-8-21-8-22-8-23-8-24-8-25-8-26-8-27-8-28-8-29-8-30-8-31-8-0-0-1-0-2-0-3-0-4-0-5-0-6-0-7-0-8-0-9-0-10-0-11-0-12-0-13-0-14-0-15-0-16-0-17-0-18-0-19-0-20-0-21-0-22-0-23-0-24-0-25-0-26-0-27-0-28-0-29-0-30-0-31-0</PointTableData>
    <DataGroupSequence>0-1-2-3-4-5-6-7</DataGroupSequence>
    <ScanABCDCode>0-1-2-3-4-5-6-7-0-0-0-0-0-0-0-0</ScanABCDCode>
    <NewScanABCDCode>0-1-2-3-4-5-6-7-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0</NewScanABCDCode>
    <RGBCode>0-1-2-3</RGBCode>
    <RowsCtrlByDataGroup>16-16-16-16-16-16-16-16</RowsCtrlByDataGroup>
    <LineBias>0</LineBias>
    <ScreenDriveType>Concurrent</ScreenDriveType>
    <SerialColorNum>0</SerialColorNum>
    <SerialDotsNumPerColor>0</SerialDotsNumPerColor>
    <SerialRGBCode>2-1-0-0</SerialRGBCode>
    <ChipMinLawRepeatNumber>1</ChipMinLawRepeatNumber>
    <ChannelEnableData>0-0</ChannelEnableData>
    <ChannelData>0-0</ChannelData>
    <ChipNumber>1</ChipNumber>
    <StartPositionOfDataGroup>0-16-0-0-0-0-0-0</StartPositionOfDataGroup>
    <ModuleVersion>2.0</ModuleVersion>
    <IsIrregular>0</IsIrregular>
    <DataGroupDriverChipNumPairArray />
    <PointTablePos />
  </Module>
</Config>